type = "webpack"
webpack_config = "node_modules/flareact/webpack"
account_id = "b0eb1f5510cb71344976cb9cac51e2af"
zone_id = "976b2978bfb8a506026238d437fe0555"

name = "website-staging"
route = "staging.devlaunchers.com/*"


[site]
bucket = "out"
entry-point = "./"